### ISSUE TITLE
Disqus Setup

### ISSUE THREAD

**Issue by loljoho** [roclin-grp/roclin-grp.github.io#34]
1. Place the following code where you'd like Disqus to load:

```html
<div id="disqus_thread"></div>
<script>

/**
*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
/*
var disqus_config = function () {
this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};
*/
(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = 'https://roclin-group.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
```

2. (Recommended) Edit the `RECOMMENDED CONFIGURATION VARIABLES` section using your CMS or platform's dynamic values. See our [documentation](https://help.disqus.com/customer/en/portal/articles/2158629) to learn why defining `identifier` and `url` is important for preventing duplicate threads.

__How to display comment count__

1. Place the following code before your site's closing `</body>` tag:
```html
<script id="dsq-count-scr" src="//roclin-group.disqus.com/count.js" async></script>
```

2. Append `#disqus_thread` to the `href` attribute in your links. This will tell Disqus which links to look up and return the comment count. For example: `<a href="http://foo.com/bar.html#disqus_thread">Link</a>`.

__Additional customisation__
See our [Adding comment count links to your home page](https://help.disqus.com/customer/portal/articles/565624) documentation.

__Credentials__
 - Email: `media@roclineage.com`
 - Password: roclin (capitalised fancy) dash year
 - https://roclin-group.disqus.com/admin/settings/general/

**Comment by mavstronaut** [comment]
Decided against using this due to cost and I would rather have conversations centered around Twitter or the cloud forum when it is released.
