### ISSUE TITLE
Company Site

### ISSUE THREAD

**Issue by mavstronaut** [roclin-grp/roclin-grp.github.io#37]
Decided
- [ ] Multiple Pages (for SEO)

TBD
- [ ] Site Layout
- [ ] Site Content Font: Times new Roman

Site Sections:
- [ ] Home (Landing, Company / Product Overview)
- [ ] About <or could it be Meet the Team> (Bio's, can help with individual personal contact)
- [x] Product
- [ ] Contact (Employment, Partner,Client) Later, this will include Support
- [ ] Blog (Updates and Articles)
- [x] Pricing (Later)

Colors
- [ ] Background #7C7287
- [ ] Navbar Background #D2EEE9
- [ ] Layer 1 (Main Content) bg #ABD6D1
- [ ] Layer 2 (Accent) #B2EDC5
- [ ] Layer 3 (Accent) #5ED0DB

**Comment by loljoho** [comment]
> Site Content Font: Times new Roman

I would recommend a sans-serif font.
