### ISSUE TITLE
index carousel

### ISSUE THREAD

**Issue by mavstronaut** [roclin-grp/roclin-grp.github.io#39]
Questions and Problem Solving:

- [ ] Carousel styling
- [ ] image stored in ~/_data/ ?
- [ ] include scripts in .md code?

index is carousel, leads to about, contact after click 
may consider underneath, set of 4 pictures and links / titles underneath img
 future links to product / whitepaper / demo / livestream (social media event) / pricing

**Comment by loljoho** [comment]
> Carousel styling

Check out the [example in the documentation](https://getbootstrap.com/docs/3.3/examples/carousel/).  Also worth checking out other Bootstrap themes out there and see how they do it.

> image stored in ~/_data/ ?

Can you clarify?

> include scripts in .md code?

What scripts?  They're imported via Liquid templating in `_includes/body/scripts.html`.

> index is carousel, leads to about, contact after click
> may consider underneath, set of 4 pictures and links / titles underneath img
> future links to product / whitepaper / demo / livestream (social media event) / pricing

Sorry, could you please try to put that into proper English and punctuate, format, etc?  Cheers.  :)

**Comment by loljoho** [comment]
I closed #40 without merging because you set `master` as the base.  

Just open a new PR with the correct base branch.

I have a bunch of comments which I'll post once you do so.
