### ISSUE TITLE
Updated Contact Form

### ISSUE THREAD

**Issue by mavstronaut** [roclin-grp/roclin-grp.github.io#44]
Replacing and removing the 3rd party Typeform extension. 

The questions as they should appear with equivalent options: https://mavrickbarona.typeform.com/to/LBuplB

I'm thinking that we could maybe remove the Yes/ No questions with checkboxes from a single question "check all that apply" to simplify. 

I do love the look and feel of the typeform, esp on mobile, it's a shame they want money for it at all hah

Removing typeform is as easy as changing layout back to cover (no footer is desired on page).
Does an AJAX request need to be made?

Also, the random blue box around the generated form is not attractive.

**Comment by loljoho** [comment]
New Issue: #46
